version: '3.8'

services:
  backend:
    build: ./backend
    container_name: akinator_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=akinator_db
      - POSTGRES_HOST=db

  frontend:
    # Теперь мы строим из Dockerfile, а не берем готовый image
    build: ./frontend
    container_name: akinator_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: akinator_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: akinator_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: